// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@4.3.0_db0@0.3.4_idb-keyval@6.2.2_ioredis@5.9.2_magicast@0.5.1_nuxt@4_d5afc240a99c7b77e65577c2b090474b/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.1_vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_terser@5.44.1_6b55acced7f23313364e41a8f455a761/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}