// Components that require browser APIs and must be rendered client-only
export const clientOnlyComponents = [
  'EvmAccount',
  'EvmAddressInput',
  'EvmArtifactModel',
  'EvmAvatar',
  'EvmConnect',
  'EvmConnectAuth',
  'EvmConnectAuthDialog',
  'EvmConnectDialog',
  'EvmConnectionStatus',
  'EvmConnectorQR',
  'EvmInAppWalletSetup',
  'EvmInAppWalletManager',
  'EvmInAppWalletUnlockDialog',
  'EvmMetaMaskQR',
  'EvmProfile',
  'EvmSidebarProfile',
  'EvmSiwe',
  'EvmSiweDialog',
  'EvmSwitchNetwork',
  'EvmMultiTransactionFlow',
  'EvmMultiTransactionFlowDialog',
  'EvmTransactionFlow',
  'EvmTransactionFlowDialog',
  'EvmWalletConnectQR',
  'EvmWalletConnectWallets',
]
